### ISSUE TITLE
Slime outer layer not changing texture

### ISSUE THREAD

**Issue by Havokmin** [Digifox03/variedMobs#11]
When trying to change the texture of a Slime's outer layer, it stays as the vanilla texture regardless of what the custom texture is. Here's a comparison of what the texture looks like in Varied Mobs vs what it should look like (running Optifine in order to show it).
![slime layer bug](https://user-images.githubusercontent.com/77683455/105059377-34cc9c80-5a45-11eb-881c-7e8f0f3ed4a5.png)

**Comment by Digifox03** [comment]
solved by 29f3d99c8f1509115e6d1aeb4e11c6915d819467 (coming with 1.17 update)
