### ISSUE TITLE
failure to work based on the example

### ISSUE THREAD

**Issue by TimelapsedEon** [Digifox03/variedMobs#5]
so I wanted a second texture to apply when a blaze is in the soul sand valley:

{
      "type": "varied-mobs:biome",
      "biome": ["minecraft:soul_sand_valley"],
      "value": "minecraft:textures/entity/blaze2.png"
}

basically just lifted from the example pack.

executing this causes my instance to reject it and unload all resource packs.

Issue #4 [Issue while loading resource packs] is also a thing on my end as well. 89,997 lines of errors in my log. I wish I was exaggerating. [https://github.com/Digifox03/variedMobs/issues/4#issue-697198579](url)

**Comment by Digifox03** [comment]
should be fixed by https://github.com/Digifox03/variedMobs/commit/e6f6a767f2e3a147eb7e80e4c2d6b27b62996969

**Comment by TNTUP** [comment]
I'm sorry by replaying on an already closed issue, I've followed the example for the varied:pick and it spits out over 74K of lines. 

Using Fabric Loader 0.13.3+build211-1.16.3. I'm on Java 8 btw

https://pastebin.com/qNafmm3P

**Comment by Digifox03** [comment]
update the mod.
