### ISSUE TITLE
[Suggestion] "type": "varied-mobs:asleep"

### ISSUE THREAD

**Issue by RyanCR03** [Digifox03/variedMobs#6]
it would be nice to have a separate eyes closed textures for villagers when they are asleep. this could be possible by detecting when a value is applied to the SleepingX, SleepingY, and SleepingZ nbt tags of the entity.

**Comment by Digifox03** [comment]
Nice idea, it will work on in for the next version.

**Comment by Digifox03** [comment]
solved by 29f3d99c8f1509115e6d1aeb4e11c6915d819467 (coming with 1.17 update)
